### ISSUE TITLE
FFT~ vs fft~

### ISSUE THREAD

**Issue by thomasfredericks** [patricksebastien/mtl#1]
There is a FFT~ and a fft~ that causes a conflict in Windows. What is the good version?

**Comment by patricksebastien** [comment]
Usually "pdoers" patch with fftw~, don't know about Windows and this conflict.
I am sure it's not helping.

**Comment by thomasfredericks** [comment]
I am talking about actual files in the repository. 
`fft~.pd` and `FFT~.pd`

**Comment by patricksebastien** [comment]
FFT~ = abstraction of mtl (maybe rename it)
fft~ = native pd lib

**Comment by thomasfredericks** [comment]
> FFT~ = abstraction of mtl (maybe rename it)
> fft~ = native pd lib

Actually :
FFT~ = abstraction of mtl (maybe rename it) - right of image
fft~ = abstraction of mtl (maybe rename it) - left of image

![2018-05-21 18_05_42-greenshot](https://user-images.githubusercontent.com/2685516/40332371-e61f5230-5d21-11e8-856e-82c1ecf594c6.png)

**Comment by patricksebastien** [comment]
Right, my local branch was very old, I renamed fft~ to fft~_argo
