### ISSUE TITLE
Can we move abstractions to a sub folder? 

### ISSUE THREAD

**Issue by thomasfredericks** [patricksebastien/mtl#2]
Can we move abstractions to a sub-folder? That way the _code_ page for the github stays shorter and cleaner. Right now, the _code_ page is way too long and mentions that items are truncated. I do not think this will break installations as Pure Data searches all sub-folders (but I am not sure).

**Comment by patricksebastien** [comment]
I think we can close this issue, you did it!
_Will test soon on linux._

**Comment by thomasfredericks** [comment]
A release was made preceding this big change.

**Comment by thomasfredericks** [comment]
A slight issue is that first mtl folder has to actually be added to pd's path.
